tool/watch-files: newer version.

diff --git a/tool/watch-files b/tool/watch-files
--- a/tool/watch-files
+++ b/tool/watch-files
@@ -1,42 +1,75 @@
 #!/usr/bin/env bash
 
 # sudo apt-get install inotify-tools
+# brew install fswatch
+
+shopt -s globstar
+pwd="$(realpath "$PWD")"
 
 files=(
-  # Makefile
-  *requirements.txt
+  Makefile
+  dev-requirements.txt
+  requirements.txt
   lib
   tests
 )
-excludes=' __pycache__'
-events=' CREATE MODIFY ATTRIB MOVE DELETE'
+excludes='__pycache__'
 
-watch_cmd=(
-  inotifywait
-  --quiet
-  --monitor
-  ${events// / --event }
-  ${excludes// / --exclude }
-  --recursive "${files[@]}"
-)
+inotifywait="$(which inotifywait 2>/dev/null | head -1)"
+fswatch="$(which fswatch 2>/dev/null| head -1)"
+
+if [[ -x "$inotifywait" ]]
+then
+  events='CREATE MODIFY ATTRIB MOVE DELETE'
+  events=" $events"
+  excludes=" $excludes"
+  read_vars='dir events file'
+  watch_cmd=(
+    $inotifywait
+    --quiet
+    --monitor
+    ${events// / --event }
+    ${excludes// / --exclude }
+    --recursive "${files[@]}"
+  )
+elif [[ -x "$fswatch" ]]
+then
+  events='Created Updated Removed'
+  includes="${files[*]}"
+  read_vars='file'
+  watch_cmd=(
+    $fswatch
+    # --quiet
+    --extended
+    ${events// / --event=}
+    --exclude=${excludes// /|}
+    --include=${includes// /|}
+    "$pwd"
+  )
+else
+  echo "cannot find inotifywait or fswatch"
+  exit 99
+fi
 
 main() {
-  file='' file_last=''
+  dir='' file='' events='' file_last=''
+  echo "${watch_cmd[*]@Q}"
   "${watch_cmd[@]}" |
-  tee /dev/stderr |
-  while file_last="$file"; read -r dir events file
+  while file_last="$file"; read -r $read_vars
   do
     file="$dir$file"
-    declare -p file events
-    [[ "$file" == "$file_last" ]] && continue
-    cmd=": i dont know what to do with ${file@Q}"
+    file="${file#$pwd/}"
+    # [[ "$file" == "$file_last" ]] && continue
+    cmd=()
+    if [[ $verbose ]]
+    then
+      declare -p file dir events
+      cmd=(: i dont know what to do with ${file@Q})
+    fi
     case "$file"
     in
-      Makefile)
+      Makefile|dev-requirements.txt|requirements.txt)
         cmd=(make all)
-        ;;
-      *requirements.txt)
-        cmd=(python -m pip install -r "$file")
         ;;
       tests/**/*.py)
         cmd=(test-py-changed "$file")
@@ -48,42 +81,60 @@ main() {
         cmd=(file-py-changed "$file")
         ;;
     esac
-    run "${cmd[@]}"
+    rtn=0
+    [[ -n "$cmd" ]] && run "${cmd[@]}"
   done
 }
 
+rtn=0
 run() {
+  rtn=0
   cat <<EOF
 
-  ###################################"
-  ### run: ${cmd[*]@Q} : ..."
+  ###################################
+  ### run: ${cmd[*]@Q}
 
 EOF
-  (set -e; "$@"); local rtn=$?
+  "$@"
+  pass-fail "$rtn" "run: ${cmd[@]}"
 cat <<EOF
 
-  ### run: ${cmd[*]@Q} : $rtn"
-  ###################################"
+  ###################################
 EOF
   return $rtn
+}
+
+cmd() {
+  echo "  ### .... . $*"
+  "$@"
+  pass-fail $? "$@"
+}
+pass-fail() {
+  if [[ $1 == 0 ]]
+  then
+    echo "  ### pass $*"
+  else
+    rtn=$1
+    echo "  ### FAIL $*"
+  fi
 }
 
 lib-py-changed() {
   local lib_file="$1"
   local test_file="tests/${lib_file#lib/}"
   file-py-changed "$lib_file"
-  run make mypy MYPY_FILES="$1"
   [[ -f "$test_file" ]] && test-py-changed "$test_file"
+  # cmd make mypy LINT_FILES="$1"
 }
 
 test-py-changed() {
+  cmd make unit-test TEST_FILES="$1"
   file-py-changed "$@"
-  run make test TEST_FILES="$1"
 }
 
 file-py-changed() {
-  run make pylint LINT_FILES="$1"
-  run make pycodestyle LINT_FILES="$1"
+  cmd make pylint LINT_FILES="$1"
+  cmd make pycodestyle LINT_FILES="$1"
 }
 
 main "$@"
